export const ecommerces = [{
    id:'-LynLz9jYS05Qm5pktMQ',
    description: 'Japan Shoe', 
    category: 'Men', 
    item: 'Men Footwear', 
    amount: 4150000, 
    image: 'shoe.png', 
    imageUrl: '../images/men_shoe1.jpg', 
    stock: 10, 
    company: 'Japan Company Ltd.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktSB',
    description: 'Baba Bata', 
    category: 'Men', 
    item: 'Men Footwear', 
    amount: 9150000, 
    image: 'shoe.png', 
    imageUrl: '../images/men_shoe2.jpg', 
    stock: 10, 
    company: 'Nigeria Limited Shoe',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktLM',
    description: 'Original Shoe', 
    category: 'Men', 
    item: 'Men Footwear', 
    amount: 24150000, 
    image: 'shoe.png', 
    imageUrl: '../images/men_shoe3.jpg', 
    stock: 10, 
    company: 'Italian Shoe Ltd.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktEE',
    description: 'Boy Clothing', 
    category: 'Boy', 
    item: 'Boy Clothe', 
    amount: 104000, 
    image: 'shoe.png', 
    imageUrl: '../images/polo_1.jpg', 
    stock: 10, 
    company: 'Shau Ltd Clothing',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktNN',
    description: 'Wears Boy', 
    category: 'Boy', 
    item: 'Boy Clothe', 
    amount: 110000, 
    image: 'boyclothe.png', 
    imageUrl: '../images/polo_2.jpg', 
    stock: 10, 
    company: 'Oshoade Wears Ltd.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktWW',
    description: 'Girl wear', 
    category: 'Girl', 
    item: 'Girl Clothe', 
    amount: 120000, 
    image: 'clothe.png', 
    imageUrl: '../images/girl_1.jpg', 
    stock: 10, 
    company: 'Shade Nigeria Limited.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktKK',
    description: 'Wear for girl', 
    category: 'Girl', 
    item: 'Men Clothe', 
    amount: 90000, 
    image: 'shoe.png', 
    imageUrl: '../images/girl_2.jpg', 
    stock: 10, 
    company: 'Ladies Company Ltd.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktQO',
    description: 'Women outfit', 
    category: 'Women', 
    item: 'Women Clothe', 
    amount: 82000, 
    image: 'cloth.png', 
    imageUrl: '../images/girl_3.jpg', 
    stock: 10, 
    company: 'Mama Bola Outfit Ltd.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktFT',
    description: 'Gogo mama', 
    category: 'Women', 
    item: 'Women Footwear', 
    amount: 211000, 
    image: 'women.png', 
    imageUrl: '../images/girl_4.jpg', 
    stock: 10, 
    company: 'Okay Mama Plc.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
},{
    id:'-LynLz9jYS05Qm5pktIU',
    description: 'Iya Bade Shoes', 
    category: 'Women', 
    item: 'Women Footwear', 
    amount: 340000, 
    image: 'shoe.png', 
    imageUrl: '../images/men_shoe4.jpg', 
    stock: 10, 
    company: 'Bade Mama Company',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
}];

export const detailProduct = [{
    id:'-LynLz9jYS05Qm5pktHJ',
    description: 'Waja Shoes', 
    category: 'Women', 
    item: 'Women Footwear', 
    amount: 250000, 
    image: 'shoe.png', 
    imageUrl: '../images/men_shoe5.jpg', 
    stock: 10, 
    company: 'Waja Company Ltd.',
    info:'The product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchaseThe product is made for men who love and desirer of good quantity foot wear product. Our product has been in exist for 50 years now with the same high quantity materials and products. We have our customers global continuely demanding for our high product. The shipment of our product to any part of the world behind 24 hours of purchase',
    inCart: false,
    count: 0,
    total: 0,
    createdAt:1000
}];

